apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core/cluster-issuer.yaml
  - smoke/smoke.yaml
  - service/auth/auth.yaml
images:
  - name: ghcr.io/liberte-top/auth-api
    newTag: latest
  - name: ghcr.io/liberte-top/auth-web
    newTag: latest
