apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-web
  namespace: service
  labels:
    app: auth-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-web
  template:
    metadata:
      labels:
        app: auth-web
    spec:
      containers:
        - name: auth-web
          image: ghcr.io/liberte-top/auth-web:sha-e7236fc
          ports:
            - containerPort: 8888
          env:
            - name: NEXT_PUBLIC_ENV
              value: "prod"
            - name: NEXT_PUBLIC_GIT_SHA
              value: "sha-33a6c24"
            - name: AUTH_API_BASE_URL
              value: "http://auth-api:3333"
            - name: NEXT_PUBLIC_AUTH_API_BASE_URL
              value: "https://auth.liberte.top"
          readinessProbe:
            httpGet:
              path: /__health__
              port: 8888
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /__health__
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
