apiVersion: v1
kind: Namespace
metadata:
  name: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-web
  namespace: service
  labels:
    app: auth-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-web
  template:
    metadata:
      labels:
        app: auth-web
    spec:
      containers:
        - name: auth-web
          image: ghcr.io/liberte-top/auth-web:sha-33a6c24
          ports:
            - containerPort: 8888
          env:
            - name: NEXT_PUBLIC_ENV
              value: "prod"
            - name: NEXT_PUBLIC_GIT_SHA
              value: "sha-33a6c24"
          readinessProbe:
            httpGet:
              path: /__health__
              port: 8888
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /__health__
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-web
  namespace: service
spec:
  selector:
    app: auth-web
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  type: ClusterIP
