apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: singbox-redirect
  namespace: service
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: singbox-cert
  namespace: service
spec:
  secretName: singbox-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - singbox.liberte.top
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: singbox-ingress
  namespace: service
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: service-singbox-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: singbox.liberte.top
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: singbox-api
                port:
                  number: 3333
          - path: /
            pathType: Prefix
            backend:
              service:
                name: singbox-web
                port:
                  number: 8888
  tls:
    - secretName: singbox-tls
      hosts:
        - singbox.liberte.top
