apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-liberte-top
  namespace: service
spec:
  secretName: auth-liberte-top-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - auth.liberte.top
