authApi:
  name: auth-api
  replicas: 2
  image:
    repository: ghcr.io/liberte-top/auth-api
    tag: latest
    pullPolicy: Always
  port: 3333
  service:
    port: 80
    targetPort: 3333
  env:
    PORT: 3333
  probes:
    readiness:
      path: /api/v1/health
      initialDelaySeconds: 2
      periodSeconds: 5
    liveness:
      path: /api/v1/health
      initialDelaySeconds: 5
      periodSeconds: 10

authWeb:
  name: auth-web
  replicas: 2
  image:
    repository: ghcr.io/liberte-top/auth-web
    tag: latest
    pullPolicy: Always
  port: 8888
  service:
    port: 80
    targetPort: 8888
  env:
    PORT: 8888
  probes:
    readiness:
      path: /
      initialDelaySeconds: 2
      periodSeconds: 5
    liveness:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 10

ingress:
  enabled: true
  name: auth
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: auth.liberte.top
      paths:
        - path: /api
          serviceName: auth-api
          servicePort: 80
        - path: /
          serviceName: auth-web
          servicePort: 80
  tls:
    - secretName: auth-tls
      hosts:
        - auth.liberte.top
