apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clash-health
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - clash.liberte.top
      secretName: clash-tls
  rules:
    - host: clash.liberte.top
      http:
        paths:
          - path: /api/v1/health
            pathType: Prefix
            backend:
              service:
                name: clash-api
                port:
                  number: 80
