apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuer.yaml
  - auth-ingress.yaml
  - clash-api-ingress.yaml
  - clash-health-ingress.yaml
  - clash-web-ingress.yaml
