apiVersion: v2
name: cert-manager
description: Cert-manager Helm wrapper
type: application
version: 0.1.0
appVersion: "1.14.4"
dependencies:
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
